### ISSUE TITLE
Cursor shift when switching from normal to insert mode

### ISSUE THREAD

**Issue by bk1285** [gerw/vim-latex-suite#18]
Hi,

I use and like the latex-suite plugin in combination with vim quite much!

However, when switching modes (normal to insert, normal to replace), every second time, the cursor will be shifted one character to the right.

Example:

Case 1:

  * Cursor over **m** in ex**m**ple
  * Press *i* to go to *insert*-mode and press **a** leads to exa**m**ple.

Repeating exacly this one more time (at another word in the text) will result here:

Case 2:

  * Cursor over **m** in ex**m**ple
  * Press *i* to go to *insert*-mode and press **a** leads to exma**p**le (cursor shifted one to the right when pressing i)

I find myself continiously alternating between case1, case 2...

Any help appreciated. :)

FYI:
vim version: 7.3.429
OS: Ubuntu 12.04

**Comment by gerw** [comment]
I cannot reproduce that behaviour.

**Comment by bk1285** [comment]
Hi gerw,

here my list of used plugins. (listed by calling :scriptnames)
Is there maybe anything suspicious? For other filetypes than tex, the issue does not occur.

  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim73/debian.vim
  3: /usr/share/vim/vim73/syntax/syntax.vim
  4: /usr/share/vim/vim73/syntax/synload.vim
  5: /usr/share/vim/vim73/syntax/syncolor.vim
  6: /usr/share/vim/vim73/filetype.vim
  7: ~/.vimrc
  8: /usr/share/vim/vim73/ftoff.vim
  9: ~/.vim/autoload/pathogen.vim
 10: /usr/share/vim/vim73/syntax/nosyntax.vim
 11: ~/.vim/bundle/git/ftdetect/git.vim
 12: /usr/share/vim/vim73/ftplugin.vim
 13: /usr/share/vim/vim73/indent.vim
 14: ~/.vim/bundle/atp/plugin/tex_atp.vim
 15: ~/.vim/bundle/fugitive/plugin/fugitive.vim
 16: ~/.vim/bundle/gundo/plugin/gundo.vim
 17: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 18: ~/.vim/bundle/nerdtree/plugin/NERD_tree.vim
 19: ~/.vim/bundle/pep8/plugin/pep8.vim
 20: ~/.vim/bundle/snipmate/plugin/snipMate.vim
 21: ~/.vim/bundle/supertab/plugin/supertab.vim
 22: ~/.vim/bundle/surround/plugin/surround.vim
 23: ~/.vim/bundle/vdebug/plugin/vdebug.vim
 24: ~/.vim/bundle/vim-latex-suite/plugin/SyntaxFolds.vim
 25: ~/.vim/bundle/vim-latex-suite/plugin/filebrowser.vim
 26: ~/.vim/bundle/vim-latex-suite/plugin/imaps.vim
 27: ~/.vim/bundle/vim-latex-suite/plugin/libList.vim
 28: ~/.vim/bundle/vim-latex-suite/plugin/remoteOpen.vim
 29: /usr/share/vim/vim73/plugin/getscriptPlugin.vim
 30: /usr/share/vim/vim73/plugin/gzip.vim
 31: /usr/share/vim/vim73/plugin/matchparen.vim
 32: /usr/share/vim/vim73/plugin/netrwPlugin.vim
 33: /usr/share/vim/vim73/plugin/rrhelper.vim
 34: /usr/share/vim/vim73/plugin/spellfile.vim
 35: /usr/share/vim/vim73/plugin/tarPlugin.vim
 36: /usr/share/vim/vim73/plugin/tohtml.vim
 37: /usr/share/vim/vim73/plugin/vimballPlugin.vim
 38: /usr/share/vim/vim73/plugin/zipPlugin.vim
 39: ~/.vim/bundle/snipmate/after/plugin/snipMate.vim
 40: ~/.vim/bundle/nerdtree/nerdtree_plugin/exec_menuitem.vim
 41: ~/.vim/bundle/nerdtree/nerdtree_plugin/fs_menu.vim

**Comment by bk1285** [comment]
Hi,
I have this https://github.com/phillipberndt/vimconfig/tree/master/bundle/vim-evince-synctex plugin in my .vim/bundle-folder, which interferes with the latex-suite. Disableing it leaves me without syncronization of pdf and latex. Do you have any latex-suite compatible solution for this?

Regards

**Comment by gerw** [comment]
Hi,

I use syncronization of pdf and latex based on `evince_vim_dbus.py`. I start gvim in a script with

    gvim --servername "$servername" "$texfile"
    evince_vim_dbus.py GVIM "$servername" "$basename.pdf" "$basename.tex"

As viewer setting in latex-suite I use synctex_wrapper, see https://github.com/gerw/vim-latex-suite/blob/master/ftplugin/latex-suite/compiler.vim#L414. `synctex_wrapper` is a simple script:

    #!/bin/bash
    pdf="$1"
    line="$2"
    column="$3"
    tex="$(basename "$4")"
    evince_vim_dbus.py EVINCE "$(basename "$pdf")" "$line" "$tex"

Hope that works.
