### ISSUE TITLE
How to add custom templates to custom place?

### ISSUE THREAD

**Issue by wkentaro** [gerw/vim-latex-suite#20]
I'd like to add some custom templates to a custom place aside from `ftplugin/latex-suite/templates` (outside the repository) to handle them cleanly. And call them with `:TTemplate` command.

Are there any good ways to achieve this?

**Comment by gerw** [comment]
You can put them into `.vim/after/ftplugin/latex-suite/templates`.

**Comment by wkentaro** [comment]
Thank you!

2015年4月4日土曜日、Gerd Wachsmuth<notifications@github.com>さんは書きました:

> You can put them into .vim/after/ftplugin/latex-suite/templates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gerw/vim-latex-suite/issues/20#issuecomment-89398128>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>
