### ISSUE TITLE
Template menu would not load

### ISSUE THREAD

**Issue by idurandiaz** [gerw/vim-latex-suite#26]
I have been using your repository with Vundle for quite some months already and it was working perfectly. However today I was configuring a new linux system and so I downloaded vim-latex-suite from your repository using vim-plug (with vundle was the same) and whenever I would open a .tex file, it would display a list of errors and when ignored, the Tex-Suite menu wouldn't load properly (missing the package, templates, and macros sub-menus). The only thing that worked for me was to replace the new vim-latex-suite folder created by my plugin manager and replace with an older one (that had installed in my mac some months ago). Now everything is running and loading smoothly once again.

Any idea why this might have happened, as for the future I would like to keep using your repository for whenever I have to reinstall/update vim-latex.

**Comment by gerw** [comment]
Thank you for your bug report. If an older version of the plugin runs seamlessly, could you try to identify the commit which introduces the trouble? Maybe `git bisect` (see https://git-scm.com/docs/git-bisect) could be of some help.

**Comment by jajadvert** [comment]
Same issue here.

**Comment by jajadvert** [comment]
I get a loop an this error report on starting up:

E121: ongedefinieerde variabele: flist
E116: ongeldige argumenten voor functie Tex_Strntok(flist, ',', i)
E15: ongeldige expressie: Tex_Strntok(flist, ',', i)
regel    5:
E121: ongedefinieerde variabele: fname
E15: ongeldige expressie: fname == ''
regel    8:
E121: ongedefinieerde variabele: fname
E15: ongeldige expressie: "amenu ".g:Tex_TemplatesMenuLocation."&".i.":<Tab>".fname." ".":call <SID>ReadTemplate('".fname."')<CR>"
regel    4:
E121: ongedefinieerde variabele: flist
E116: ongeldige argumenten voor functie Tex_Strntok(flist, ',', i)
E15: ongeldige expressie: Tex_Strntok(flist, ',', i)
regel    5:
E121: ongedefinieerde variabele: fname
E15: ongeldige expressie: fname == ''
regel    8:
E121: ongedefinieerde variabele: fname
E15: ongeldige expressie: "amenu ".g:Tex_TemplatesMenuLocation."&".i.":<Tab>".fname." ".":call <SID>ReadTemplate('".fname."')<CR>"
regel    4:
E121: ongedefinieerde variabele: flist
E116: ongeldige argumenten voor functie Tex_Strntok(flist, ',', i)
E15: ongeldige expressie: Tex_Strntok(flist, ',', i)
regel    5:
E121: ongedefinieerde variabele: fname
E15: ongeldige expressie: fname == ''
regel    8:
E121: ongedefinieerde variabele: fname
E15: ongeldige expressie: "amenu ".g:Tex_TemplatesMenuLocation."&".i.":<Tab>".fname." ".":call <SID>ReadTemplate('".fname."')<CR>"
regel    4:
E121: ongedefinieerde variabele: flist
E116: ongeldige argumenten voor functie Tex_Strntok(flist, ',', i)
E15: ongeldige expressie: Tex_Strntok(flist, ',', i)
regel    5:
E121: ongedefinieerde variabele: fname
E15: ongeldige expressie: fname == ''

ad infinitum

**Comment by gerw** [comment]
Thank you for the report. I found and fixed the issue.

**Comment by idurandiaz** [comment]
great, thanks!
