### ISSUE TITLE
Support for cleveref

### ISSUE THREAD

**Issue by khatchad** [gerw/vim-latex-suite#35]
The cleveref package doesn't seem to be fully supported. For example, `\cref` commands are not treated the same as `\ref`. The syntax highlighting is different and spell check is making the labels as incorrectly spelled (it doesn't do that for `\ref`).

**Comment by gerw** [comment]
The latex-suite does not provide *any* syntax highlighting. The standard syntax highlighting of vim for LaTeX does not know cleveref. However, you can use https://github.com/gerw/vim-tex-syntax for improving the syntax highlighting.

**Comment by gerw** [comment]
What do you mean by autocompletion?

**Comment by khatchad** [comment]
F9 should bring up labels after \ref{, in latex-suite, I believe.

**Comment by gerw** [comment]
Completion of `\cref` does work with latex-suite.

**Comment by khatchad** [comment]
Ah, ok, just must be my machine then.
